config/routes.rb
Rails.application.routes.draw do
  resources :arduinos do
    member do
      post :turn_led_on
      post :turn_led_off
    end
  end
  namespace :api do
    namespace :v1 do
      resources :arduinos
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arduino.rb
class Arduino < ApplicationRecord
  validates :uid, :ip, :port, presence: true

  def turn_led_on
    request "digital/8/o"
    request "digital/8/1"
  end

  def turn_led_off
    request "digital/8/0"
  end  

  def request path
    HTTParty.get("http://#{self.ip}:#{self.port}/#{path}")
  end
end

app/controllers/api/v1/arduinos_controller.rb
class Api::V1::ArduinosController < Api::V1::BaseController
  before_action :set_arduino, only: [:show, :edit, :update, :destroy]

  # GET /arduinos
  # GET /arduinos.json
  def index
    @arduinos = Arduino.all
  end

  # GET /arduinos/1
  # GET /arduinos/1.json
  def show
  end

  # GET /arduinos/new
  def new
    @arduino = Arduino.new
  end

  # GET /arduinos/1/edit
  def edit
  end

  # POST /arduinos
  # POST /arduinos.json
  def create
    @arduino = Arduino.new(arduino_params)

    respond_to do |format|
      if @arduino.save
        format.html { redirect_to @arduino, notice: 'Arduino was successfully created.' }
        format.json { render :show, status: :created, location: @arduino }
      else
        format.html { render :new }
        format.json { render json: @arduino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arduinos/1
  # PATCH/PUT /arduinos/1.json
  def update
    respond_to do |format|
      if @arduino.update(arduino_params)
        format.html { redirect_to @arduino, notice: 'Arduino was successfully updated.' }
        format.json { render :show, status: :ok, location: @arduino }
      else
        format.html { render :edit }
        format.json { render json: @arduino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arduinos/1
  # DELETE /arduinos/1.json
  def destroy
    @arduino.destroy
    respond_to do |format|
      format.html { redirect_to arduinos_url, notice: 'Arduino was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arduino
      @arduino = Arduino.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arduino_params
      params.permit(:uid)
    end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_default_response_format

  def set_default_response_format
    request.format = :json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/arduinos_controller.rb
class ArduinosController < ApplicationController
  before_action :set_arduino, only: [:show, :edit, :update, :destroy, :turn_led_on, :turn_led_off]

  # GET /arduinos
  # GET /arduinos.json
  def index
    @arduinos = Arduino.all
  end

  # GET /arduinos/1
  # GET /arduinos/1.json
  def show
  end

  # GET /arduinos/new
  def new
    @arduino = Arduino.new
  end

  # GET /arduinos/1/edit
  def edit
  end

  # POST /arduinos
  # POST /arduinos.json
  def create
    @arduino = Arduino.new(arduino_params)

    respond_to do |format|
      if @arduino.save
        format.html { redirect_to @arduino, notice: 'Arduino was successfully created.' }
        format.json { render :show, status: :created, location: @arduino }
      else
        format.html { render :new }
        format.json { render json: @arduino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arduinos/1
  # PATCH/PUT /arduinos/1.json
  def update
    respond_to do |format|
      if @arduino.update(arduino_params)
        format.html { redirect_to @arduino, notice: 'Arduino was successfully updated.' }
        format.json { render :show, status: :ok, location: @arduino }
      else
        format.html { render :edit }
        format.json { render json: @arduino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arduinos/1
  # DELETE /arduinos/1.json
  def destroy
    @arduino.destroy
    respond_to do |format|
      format.html { redirect_to arduinos_url, notice: 'Arduino was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def turn_led_on
    @arduino.turn_led_on
    redirect_to arduinos_url
  end

  def turn_led_off
    @arduino.turn_led_off
    redirect_to arduinos_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arduino
      @arduino = Arduino.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arduino_params
      params.require(:arduino).permit(:uid, :ip, :port)
    end
end

app/helpers/api/v1/arduinos_helper.rb
module Api::V1::ArduinosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arduinos_helper.rb
module ArduinosHelper
end

app/views/arduinos/_form.html.erb
<%= form_for(arduino) do |f| %>
  <% if arduino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arduino.errors.count, "error") %> prohibited this arduino from being saved:</h2>

      <ul>
      <% arduino.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %>
    <%= f.text_field :uid %>
  </div>

  <div class="field">
    <%= f.label :ip %>
    <%= f.text_field :ip %>
  </div>

  <div class="field">
    <%= f.label :port %>
    <%= f.text_field :port %>
  </div>  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arduinos/edit.html.erb
<h1>Editing Arduino</h1>

<%= render 'form', arduino: @arduino %>

<%= link_to 'Show', @arduino %> |
<%= link_to 'Back', arduinos_path %>

app/views/arduinos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arduinos</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arduinos.each do |arduino| %>
      <tr>
        <td><%= arduino.uid %></td>
        <td><%= link_to 'Show', arduino %></td>
        <td><%= link_to 'Edit', edit_arduino_path(arduino) %></td>
        <td><%= link_to 'TurnLedOn', turn_led_on_arduino_path(arduino), method: :post %></td>
        <td><%= link_to 'TurnLedOff', turn_led_off_arduino_path(arduino), method: :post %></td>
        <td><%= link_to 'Destroy', arduino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arduino', new_arduino_path %>

app/views/arduinos/new.html.erb
<h1>New Arduino</h1>

<%= render 'form', arduino: @arduino %>

<%= link_to 'Back', arduinos_path %>

app/views/arduinos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @arduino.uid %>
</p>

<%= link_to 'Edit', edit_arduino_path(@arduino) %> |
<%= link_to 'Back', arduinos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jucuzona</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>